/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase } from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(name: "Donation", signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Donation__factory>;

    getContractAt(name: "Donation", address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Donation>;

    deployContract(name: "Donation", signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Donation>;

    deployContract(name: "Donation", args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Donation>;

    // default types
    getContractFactory(name: string, signerOrOptions?: ethers.Signer | FactoryOptions): Promise<ethers.ContractFactory>;
    getContractFactory(abi: any[], bytecode: ethers.BytesLike, signer?: ethers.Signer): Promise<ethers.ContractFactory>;
    getContractAt(nameOrAbi: string | any[], address: string | ethers.Addressable, signer?: ethers.Signer): Promise<ethers.Contract>;
    deployContract(name: string, signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<ethers.Contract>;
    deployContract(name: string, args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<ethers.Contract>;
  }
}
