/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Donation } from "./Donation";
export * as factories from "./factories";
export { Donation__factory } from "./factories/Donation__factory";
